[[servers]]
  Address = "tcp://172.16.205.10:2002"
  Suite = "Ed25519"
  Public = "e65a2a74ddbfa1712192b2048707345822989bdf9cf73b35d18e1366017ae3dd"
  Description = "Unlynx Server 0"
[[servers]]
  Address = "tcp://172.16.205.11:2004"
  Suite = "Ed25519"
  Public = "504f7f48a57acf0dcf7b3771cc38855f31bbefaa504574f6f92c97a20ee4e837"
  Description = "Unlynx Server 1"
[[servers]]
  Address = "tcp://172.16.205.12:2006"
  Suite = "Ed25519"
  Public = "2c5195464fe086f21e1b0205bff64014ab4cd9459c8d2ca9695c7460039d90c5"
  Description = "Unlynx Server 2"
